In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [5]:
df2 = pd.read_csv('total.csv')

In [12]:
df2.head()

,macaddr,600,601,602,603,604,605,606,607,608,...,2700,2701,2800,2801,2900,2901,3000,3001,3100,3101
0,14b2a675106d77447c58c15e1622,521.0,522.0,523.0,0.0,0.0,0.0,0.0,0.0,0.0,...,458.0,459.0,0.0,0.0,700.0,701.0,0.0,0.0,500.000000,501.0
1,14d1d5a1376797527ed5aaf7ff5557,0.0,0.0,0.0,0.0,0.0,0.0,0.0,930.0,929.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,1627423d9cccd03bea7ef140db2b96a7,1391.0,1392.0,1393.0,0.0,1618.0,1619.0,1589.5,1560.0,1561.0,...,1394.0,1395.0,1339.0,0.0,3046.0,0.0,1549.0,1550.0,1497.000000,1498.0
3,18a5ac58309de599e7612ecae529cd26,1660.0,0.0,1914.0,1915.0,1916.0,0.0,0.0,0.0,0.0,...,1752.0,0.0,0.0,1957.0,0.0,0.0,1831.0,0.0,2019.666667,2020.0
4,1fa232db487558e17dbf1d9da177c1,2614.0,2615.0,2616.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2524.0,2525.0,2536.000000,2537.0

In [17]:
list(range(1,5))

[1, 2, 3, 4]

In [18]:
for i in df2:
    if i=='macaddr': continue
    for j in range(27605):
        if df2.loc[j, i]>0: df2.loc[j, i] = 1

KeyboardInterrupt:

In [145]:
df2.head()
# df2.to_csv('./total2.csv', index=False)

,macaddr,600,601,602,603,604,605,606,607,608,...,2700,2701,2800,2801,2900,2901,3000,3001,3100,3101
0,14b2a675106d77447c58c15e1622,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,458.0,459.0,0.0,0.0,700.0,701.0,0.0,0.0,500.000000,501.0
1,14d1d5a1376797527ed5aaf7ff5557,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,1627423d9cccd03bea7ef140db2b96a7,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1394.0,1395.0,1339.0,0.0,3046.0,0.0,1549.0,1550.0,1497.000000,1498.0
3,18a5ac58309de599e7612ecae529cd26,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1752.0,0.0,0.0,1957.0,0.0,0.0,1831.0,0.0,2019.666667,2020.0
4,1fa232db487558e17dbf1d9da177c1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2524.0,2525.0,2536.000000,2537.0

In [147]:
dd = df2.as_matrix()
dd = dd.flatten()

print(len(dd))

for idx, el in enumerate(dd):
    if type(el) is not str and el>0:
        dd[idx] = 1

In [150]:
dd2 = dd.reshape(27605, 625)

In [151]:
df3 = pd.DataFrame(dd2, columns=df2.columns)
df3.head()

,macaddr,600,601,602,603,604,605,606,607,608,...,2700,2701,2800,2801,2900,2901,3000,3001,3100,3101
0,a0717a5ff3d79f8351698315a6b1fdb3,1,1,1,0,0,0,0,0,0,...,0,0,0,0,1,1,1,0,0,0
1,4b69f1c94d6dac1565de9c90825b807c,1,1,1,0,0,0,1,1,1,...,1,0,1,0,0,0,1,1,1,0
2,89e537c78341378358c7e9cb2a4709e,1,1,1,0,0,0,1,0,1,...,0,1,1,0,1,1,1,1,1,1
3,b3552b40af9af94c891ede96c5de5a,1,1,1,1,1,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
4,7fcb9b64d524ecb132aab2afda71aca,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1

In [158]:
df3 = pd.read_csv('total_ch.csv')

In [159]:
df3=df3.rename(columns = {'1101_re':'1200'})

In [117]:
df3.to_csv('./total2.csv', index=False)

In [61]:
from pprint import pprint

In [160]:
li = list(df3.columns)
# li = li.sort()

In [161]:
li.sort()
pprint(li)

['1000',
 '1001',
 '1002',
 '1003',
 '1004',
 '1005',
 '1006',
 '1007',
 '1008',
 '1009',
 '1010',
 '1011',
 '1012',
 '1013',
 '1014',
 '1015',
 '1016',
 '1017',
 '1018',
 '1019',
 '1020',
 '1021',
 '1022',
 '1023',
 '1100',
 '1101',
 '1102',
 '1103',
 '1104',
 '1105',
 '1106',
 '1107',
 '1108',
 '1109',
 '1110',
 '1111',
 '1112',
 '1113',
 '1114',
 '1115',
 '1116',
 '1117',
 '1118',
 '1119',
 '1120',
 '1121',
 '1122',
 '1123',
 '1200',
 '1201',
 '1202',
 '1203',
 '1204',
 '1205',
 '1206',
 '1207',
 '1208',
 '1209',
 '1210',
 '1211',
 '1212',
 '1213',
 '1214',
 '1215',
 '1216',
 '1217',
 '1218',
 '1219',
 '1220',
 '1221',
 '1222',
 '1223',
 '1300',
 '1301',
 '1302',
 '1303',
 '1304',
 '1305',
 '1306',
 '1307',
 '1308',
 '1309',
 '1310',
 '1311',
 '1312',
 '1313',
 '1314',
 '1315',
 '1316',
 '1317',
 '1318',
 '1319',
 '1320',
 '1321',
 '1322',
 '1323',
 '1400',
 '1401',
 '1402',
 '1403',
 '1404',
 '1405',
 '1406',
 '1407',
 '1408',
 '1409',
 '1410',
 '1411',
 '1412',
 '1413',
 '1414',
 '1415',
 '1416',
 '1417',
 '1418',
 '1419',
 '1420',
 '1421',
 '1422',
 '1423',
 '1500',
 '1501',
 '1502',
 '1503',
 '1504',
 '1505',
 '1506',
 '1507',
 '1508',
 '1509',
 '1510',
 '1511',
 '1512',
 '1513',
 '1514',
 '1515',
 '1516',
 '1517',
 '1518',
 '1519',
 '1520',
 '1521',
 '1522',
 '1523',
 '1600',
 '1601',
 '1602',
 '1603',
 '1604',
 '1605',
 '1606',
 '1607',
 '1608',
 '1609',
 '1610',
 '1611',
 '1612',
 '1613',
 '1614',
 '1615',
 '1616',
 '1617',
 '1618',
 '1619',
 '1620',
 '1621',
 '1622',
 '1623',
 '1700',
 '1701',
 '1702',
 '1703',
 '1704',
 '1705',
 '1706',
 '1707',
 '1708',
 '1709',
 '1710',
 '1711',
 '1712',
 '1713',
 '1714',
 '1715',
 '1716',
 '1717',
 '1718',
 '1719',
 '1720',
 '1721',
 '1722',
 '1723',
 '1800',
 '1801',
 '1802',
 '1803',
 '1804',
 '1805',
 '1806',
 '1807',
 '1808',
 '1809',
 '1810',
 '1811',
 '1812',
 '1813',
 '1814',
 '1815',
 '1816',
 '1817',
 '1818',
 '1819',
 '1820',
 '1821',
 '1822',
 '1823',
 '1900',
 '1901',
 '1902',
 '1903',
 '1904',
 '1905',
 '1906',
 '1907',
 '1908',
 '1909',
 '1910',
 '1911',
 '1912',
 '1913',
 '1914',
 '1915',
 '1916',
 '1917',
 '1918',
 '1919',
 '1920',
 '1921',
 '1922',
 '1923',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2100',
 '2101',
 '2102',
 '2103',
 '2104',
 '2105',
 '2106',
 '2107',
 '2108',
 '2109',
 '2110',
 '2111',
 '2112',
 '2113',
 '2114',
 '2115',
 '2116',
 '2117',
 '2118',
 '2119',
 '2120',
 '2121',
 '2122',
 '2123',
 '2200',
 '2201',
 '2202',
 '2203',
 '2204',
 '2205',
 '2206',
 '2207',
 '2208',
 '2209',
 '2210',
 '2211',
 '2212',
 '2213',
 '2214',
 '2215',
 '2216',
 '2217',
 '2218',
 '2219',
 '2220',
 '2221',
 '2222',
 '2223',
 '2300',
 '2301',
 '2302',
 '2303',
 '2304',
 '2305',
 '2306',
 '2307',
 '2308',
 '2309',
 '2310',
 '2311',
 '2312',
 '2313',
 '2314',
 '2315',
 '2316',
 '2317',
 '2318',
 '2319',
 '2320',
 '2321',
 '2322',
 '2323',
 '2400',
 '2401',
 '2402',
 '2403',
 '2404',
 '2405',
 '2406',
 '2407',
 '2408',
 '2409',
 '2410',
 '2411',
 '2412',
 '2413',
 '2414',
 '2415',
 '2416',
 '2417',
 '2418',
 '2419',
 '2420',
 '2421',
 '2422',
 '2423',
 '2500',
 '2501',
 '2502',
 '2503',
 '2504',
 '2505',
 '2506',
 '2507',
 '2508',
 '2509',
 '2510',
 '2511',
 '2512',
 '2513',
 '2514',
 '2515',
 '2516',
 '2517',
 '2518',
 '2519',
 '2520',
 '2521',
 '2522',
 '2523',
 '2600',
 '2601',
 '2602',
 '2603',
 '2604',
 '2605',
 '2606',
 '2607',
 '2608',
 '2609',
 '2610',
 '2611',
 '2612',
 '2613',
 '2614',
 '2615',
 '2616',
 '2617',
 '2618',
 '2619',
 '2620',
 '2621',
 '2622',
 '2623',
 '2700',
 '2701',
 '2702',
 '2703',
 '2704',
 '2705',
 '2706',
 '2707',
 '2708',
 '2709',
 '2710',
 '2711',
 '2712',
 '2713',
 '2714',
 '2715',
 '2716',
 '2717',
 '2718',
 '2719',
 '2720',
 '2721',
 '2722',
 '2723',
 '2800',
 '2801',
 '2802',
 '2803',
 '2804',
 '2805',
 '2806',
 '2807',
 '2808',
 '2809',
 '2810',
 '2811',
 '2812',
 '2813',
 '2814',
 '2815',
 '2816',
 '2817',
 '2818',
 '2819',
 '2820',
 '2821',
 '2822',
 '2823',
 '2900',
 '2901',
 '2902',
 '2903',
 '2904',
 '2905',
 '2906',
 '2907',
 '2908',
 '2909',
 '2910',
 '2911',
 '2912',
 '2913',
 '2914',
 '2915',
 '2916',
 '2917',
 '2918',
 '2919',
 '2920',
 '2921',
 '2922',
 '2923',
 '3000',
 '3001',
 '3002',
 '3003',
 '3004',
 '3005',
 '3006',
 '3007',
 '3008',
 '3009',
 '3010',
 '3011',
 '3012',
 '3013',
 '3014',
 '3015',
 '3016',
 '3017',
 '3018',
 '3019',
 '3020',
 '3021',
 '3022',
 '3023',
 '3100',
 '3101',
 '3102',
 '3103',
 '3104',
 '3105',
 '3106',
 '3107',
 '3108',
 '3109',
 '3110',
 '3111',
 '3112',
 '3113',
 '3114',
 '3115',
 '3116',
 '3117',
 '3118',
 '3119',
 '3120',
 '3121',
 '3122',
 '3123',
 '600',
 '601',
 '602',
 '603',
 '604',
 '605',
 '606',
 '607',
 '608',
 '609',
 '610',
 '611',
 '612',
 '613',
 '614',
 '615',
 '616',
 '617',
 '618',
 '619',
 '620',
 '621',
 '622',
 '623',
 '700',
 '701',
 '702',
 '703',
 '704',
 '705',
 '706',
 '707',
 '708',
 '709',
 '710',
 '711',
 '712',
 '713',
 '714',
 '715',
 '716',
 '717',
 '718',
 '719',
 '720',
 '721',
 '722',
 '723',
 '800',
 '801',
 '802',
 '803',
 '804',
 '805',
 '806',
 '807',
 '808',
 '809',
 '810',
 '811',
 '812',
 '813',
 '814',
 '815',
 '816',
 '817',
 '818',
 '819',
 '820',
 '821',
 '822',
 '823',
 '900',
 '901',
 '902',
 '903',
 '904',
 '905',
 '906',
 '907',
 '908',
 '909',
 '910',
 '911',
 '912',
 '913',
 '914',
 '915',
 '916',
 '917',
 '918',
 '919',
 '920',
 '921',
 '922',
 '923',
 'macaddr']

In [162]:
li2 = [li[-1]]+li[22*24:-1]+li[:22*24]

In [164]:
df3 = df3.reindex_axis(li2, axis=1)
df3.head()

,macaddr,600,601,602,603,604,605,606,607,608,...,3114,3115,3116,3117,3118,3119,3120,3121,3122,3123
0,a0717a5ff3d79f8351698315a6b1fdb3,727,727,727,0,0,0,0,0,0,...,727,727,727,0,0,0,0,0,0,0
1,4b69f1c94d6dac1565de9c90825b807c,838,838,838,0,0,0,838,838,838,...,0,0,0,0,0,817,817,817,817,817
2,89e537c78341378358c7e9cb2a4709e,466,466,466,0,0,0,178,0,141,...,178,0,0,0,0,816,0,839,0,0
3,b3552b40af9af94c891ede96c5de5a,430,430,430,195,195,0,0,838,838,...,838,838,0,0,838,838,838,838,0,0
4,7fcb9b64d524ecb132aab2afda71aca,430,138,442,430,430,442,442,138,138,...,0,0,0,473,473,839,817,839,430,430

In [165]:
y = pd.read_csv('label.csv')

In [166]:
y_temp = [0]*len(df3)
for idx,el in enumerate(df3['macaddr']):
    for j in y['macaddr']:
        if el==j:
            y_temp[idx]=1
            break;

In [167]:
sum(y_temp)

1915

In [168]:
df3['y'] = y_temp

In [169]:
df3.head()

,macaddr,600,601,602,603,604,605,606,607,608,...,3115,3116,3117,3118,3119,3120,3121,3122,3123,y
0,a0717a5ff3d79f8351698315a6b1fdb3,727,727,727,0,0,0,0,0,0,...,727,727,0,0,0,0,0,0,0,0
1,4b69f1c94d6dac1565de9c90825b807c,838,838,838,0,0,0,838,838,838,...,0,0,0,0,817,817,817,817,817,1
2,89e537c78341378358c7e9cb2a4709e,466,466,466,0,0,0,178,0,141,...,0,0,0,0,816,0,839,0,0,0
3,b3552b40af9af94c891ede96c5de5a,430,430,430,195,195,0,0,838,838,...,838,0,0,838,838,838,838,0,0,0
4,7fcb9b64d524ecb132aab2afda71aca,430,138,442,430,430,442,442,138,138,...,0,0,473,473,839,817,839,430,430,0

In [172]:
df3_0 = df3.sample(frac=1)[df3['y']==0].iloc[:4000,:]
df3_1 = df3[df3['y']==1].iloc[:,:]
df4 = pd.concat([df3_0, df3_1], axis=0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [173]:
print(df4.shape)
df4.to_csv('./total3.csv', index=False)

(5915, 626)

In [139]:
len(df3_0)

4000

In [124]:
df3['y'][12334] == 1

False

In [119]:
1915/27605

0.06937149067197972

---
## 이건 전체모델

In [2]:
df = pd.read_csv('nn_project_10p_f.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.head()

,macaddr,sessionId,logId,channel,view_start,duration,dayOfMonth,hourOfDay,minuteOfDay,terminated_date,account_age,terminated
0,11fbc038e6c49c65d0af7748fbb8,13481980,17179962320,154,2016-05-22T18:24:00.000+09:00,120,22,18,1104,NaN,NaN,NaN
1,11fbc038e6c49c65d0af7748fbb8,13481997,17179962339,357,2016-05-25T22:44:00.000+09:00,15,25,22,1364,NaN,NaN,NaN
2,11fbc038e6c49c65d0af7748fbb8,13482010,17179962360,457,2016-05-28T13:00:00.000+09:00,120,28,13,780,NaN,NaN,NaN
3,11fbc038e6c49c65d0af7748fbb8,13481947,17179962279,147,2016-05-16T02:00:00.000+09:00,60,16,2,120,NaN,NaN,NaN
4,11fbc038e6c49c65d0af7748fbb8,13481944,17179962276,139,2016-05-15T13:31:00.000+09:00,89,15,13,811,NaN,NaN,NaN

In [4]:
data.info()

NameError: name 'data' is not defined

In [18]:
df_ = data.dropna()

In [19]:
len(df_)
df_.head()

,macaddr,sessionId,logId,channel,view_start,duration,dayOfMonth,hourOfDay,minuteOfDay,terminated_date,account_age,terminated
5556525,2743f53ef5cbc0f2fa9ad9c2e36014a9,51056,171799131861,138,2016-05-15T20:00:00.000+09:00,120,15,20,1200,2016-06-01,1097.0,1.0
5556526,c90debf209fa7e948333633655442e3,65848,1340029850378,727,2016-05-17T06:44:00.000+09:00,8,17,6,404,2016-07-15,1887.0,1.0
5556527,d137cb1ab951db1e97a3bc7be54633ca,69976,1391569584477,817,2016-05-16T12:29:00.000+09:00,120,16,12,749,2016-06-10,185.0,1.0
5556528,b2ed1be554b92ae66feb5cda78d63e5,179205,1176821401145,194,2016-05-26T18:00:00.000+09:00,120,26,18,1080,2016-07-04,1190.0,1.0
5556529,b22013ec5749f454adbc3e2444477b2b,191860,1176821086829,195,2016-05-23T10:00:00.000+09:00,120,23,10,600,2016-06-27,1672.0,1.0

In [6]:
# df2 = df.sample(frac=1).reset_index(drop=True)
len(set(df['macaddr']))

27605

In [10]:
# 필요없는 칼럼제거, Nan 0으로 채우기
df = df.drop(['sessionId', 'logId', 'terminated_date', 'account_age'], axis=1).fillna(0)

In [19]:
# macaddr 갯수 
mac = list(set(df['macaddr']))
len(mac)

27605

In [22]:
for i in mac:
    df_m = df[df['macaddr']==i]

23.8

In [23]:
kk = df[df['macaddr']=='b22013ec5749f454adbc3e2444477b2b']

In [41]:
len(kk)

185

In [36]:
len(kk)
kk = kk.sort_values(by=['view_start'])
for i in range(len(kk)):
    print(list(kk.iloc[i]))
    for d in range(6,32):
        if

['b22013ec5749f454adbc3e2444477b2b', 442, '2016-05-06T00:00:00.000+09:00', 120, 6, 0, 0, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-06T08:33:00.000+09:00', 27, 6, 8, 513, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-06T09:39:00.000+09:00', 120, 6, 9, 579, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 138, '2016-05-06T20:20:00.000+09:00', 99, 6, 20, 1220, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-06T23:05:00.000+09:00', 55, 6, 23, 1385, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-07T01:00:00.000+09:00', 120, 7, 1, 60, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-07T11:00:00.000+09:00', 120, 7, 11, 660, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 442, '2016-05-07T14:14:00.000+09:00', 46, 7, 14, 854, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 442, '2016-05-07T16:00:00.000+09:00', 120, 7, 16, 960, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-07T18:11:00.000+09:00', 49, 7, 18, 1091, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-07T20:46:00.000+09:00', 65, 7, 20, 1246, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-07T21:52:00.000+09:00', 8, 7, 21, 1312, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-07T22:27:00.000+09:00', 38, 7, 22, 1347, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-07T23:07:00.000+09:00', 6, 7, 23, 1387, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-07T23:16:00.000+09:00', 44, 7, 23, 1396, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-08T01:00:00.000+09:00', 120, 8, 1, 60, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-08T07:00:00.000+09:00', 120, 8, 7, 420, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-08T15:00:00.000+09:00', 10, 8, 15, 900, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-08T15:12:00.000+09:00', 6, 8, 15, 912, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 459, '2016-05-08T15:23:00.000+09:00', 8, 8, 15, 923, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-08T16:05:00.000+09:00', 19, 8, 16, 965, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 189, '2016-05-08T16:25:00.000+09:00', 95, 8, 16, 985, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-08T20:00:00.000+09:00', 18, 8, 20, 1200, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-08T20:18:00.000+09:00', 5, 8, 20, 1218, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-08T20:28:00.000+09:00', 7, 8, 20, 1228, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-08T20:39:00.000+09:00', 5, 8, 20, 1239, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-08T22:04:00.000+09:00', 120, 8, 22, 1324, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-09T04:04:00.000+09:00', 120, 9, 4, 244, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-09T19:37:00.000+09:00', 12, 9, 19, 1177, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-09T19:49:00.000+09:00', 33, 9, 19, 1189, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-09T20:22:00.000+09:00', 34, 9, 20, 1222, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-09T21:10:00.000+09:00', 120, 9, 21, 1270, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-10T21:10:00.000+09:00', 120, 10, 21, 1270, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-11T08:32:00.000+09:00', 120, 11, 8, 512, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-11T15:00:00.000+09:00', 120, 11, 15, 900, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-11T18:00:00.000+09:00', 60, 11, 18, 1080, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-11T19:53:00.000+09:00', 41, 11, 19, 1193, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-11T20:39:00.000+09:00', 21, 11, 20, 1239, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-11T23:00:00.000+09:00', 120, 11, 23, 1380, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-12T09:00:00.000+09:00', 120, 12, 9, 540, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-12T16:00:00.000+09:00', 120, 12, 16, 960, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-12T19:48:00.000+09:00', 12, 12, 19, 1188, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 138, '2016-05-12T20:37:00.000+09:00', 43, 12, 20, 1237, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-12T21:28:00.000+09:00', 23, 12, 21, 1288, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-12T21:51:00.000+09:00', 8, 12, 21, 1311, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-12T22:19:00.000+09:00', 41, 12, 22, 1339, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-13T00:00:00.000+09:00', 120, 13, 0, 0, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-13T16:00:00.000+09:00', 120, 13, 16, 960, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-13T19:52:00.000+09:00', 31, 13, 19, 1192, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-13T20:28:00.000+09:00', 32, 13, 20, 1228, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-13T21:31:00.000+09:00', 120, 13, 21, 1291, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-14T08:51:00.000+09:00', 29, 14, 8, 531, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-14T09:20:00.000+09:00', 40, 14, 9, 560, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-14T11:00:00.000+09:00', 120, 14, 11, 660, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-14T17:00:00.000+09:00', 39, 14, 17, 1020, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-14T17:42:00.000+09:00', 6, 14, 17, 1062, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-14T17:48:00.000+09:00', 120, 14, 17, 1068, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-14T23:00:00.000+09:00', 18, 14, 23, 1380, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-14T23:18:00.000+09:00', 42, 14, 23, 1398, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-15T04:00:00.000+09:00', 120, 15, 4, 240, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-15T07:00:00.000+09:00', 60, 15, 7, 420, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-15T11:00:00.000+09:00', 23, 15, 11, 660, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-15T11:26:00.000+09:00', 7, 15, 11, 686, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-15T11:33:00.000+09:00', 120, 15, 11, 693, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-15T16:00:00.000+09:00', 60, 15, 16, 960, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-15T18:00:00.000+09:00', 120, 15, 18, 1080, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-15T22:00:00.000+09:00', 120, 15, 22, 1320, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-16T05:00:00.000+09:00', 120, 16, 5, 300, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-16T11:33:00.000+09:00', 120, 16, 11, 693, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-16T17:00:00.000+09:00', 120, 16, 17, 1020, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-17T00:00:00.000+09:00', 12, 17, 0, 0, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-17T00:14:00.000+09:00', 18, 17, 0, 14, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-17T00:32:00.000+09:00', 28, 17, 0, 32, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-17T05:00:00.000+09:00', 60, 17, 5, 300, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-17T09:00:00.000+09:00', 60, 17, 9, 540, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-17T11:00:00.000+09:00', 120, 17, 11, 660, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-17T15:00:00.000+09:00', 120, 17, 15, 900, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-17T21:00:00.000+09:00', 60, 17, 21, 1260, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 310, '2016-05-17T23:03:00.000+09:00', 12, 17, 23, 1383, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-17T23:15:00.000+09:00', 10, 17, 23, 1395, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 310, '2016-05-17T23:32:00.000+09:00', 10, 17, 23, 1412, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-17T23:42:00.000+09:00', 10, 17, 23, 1422, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-17T23:53:00.000+09:00', 7, 17, 23, 1433, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-18T00:06:00.000+09:00', 114, 18, 0, 6, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-18T03:00:00.000+09:00', 60, 18, 3, 180, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-18T05:00:00.000+09:00', 60, 18, 5, 300, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-18T07:00:00.000+09:00', 120, 18, 7, 420, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-18T18:00:00.000+09:00', 72, 18, 18, 1080, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-18T19:12:00.000+09:00', 37, 18, 19, 1152, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-18T19:50:00.000+09:00', 10, 18, 19, 1190, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-18T20:50:00.000+09:00', 120, 18, 20, 1250, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-19T04:00:00.000+09:00', 120, 19, 4, 240, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-19T09:00:00.000+09:00', 120, 19, 9, 540, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-19T12:00:00.000+09:00', 120, 19, 12, 720, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-19T17:00:00.000+09:00', 60, 19, 17, 1020, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-19T19:00:00.000+09:00', 60, 19, 19, 1140, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-19T20:50:00.000+09:00', 70, 19, 20, 1250, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-20T03:00:00.000+09:00', 120, 20, 3, 180, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-20T12:00:00.000+09:00', 120, 20, 12, 720, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-20T17:00:00.000+09:00', 120, 20, 17, 1020, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-20T19:23:00.000+09:00', 26, 20, 19, 1163, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-20T19:49:00.000+09:00', 11, 20, 19, 1189, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-20T20:59:00.000+09:00', 23, 20, 20, 1259, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-20T21:24:00.000+09:00', 12, 20, 21, 1284, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-20T21:37:00.000+09:00', 83, 20, 21, 1297, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-21T01:00:00.000+09:00', 120, 21, 1, 60, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-21T17:00:00.000+09:00', 60, 21, 17, 1020, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-21T19:00:00.000+09:00', 120, 21, 19, 1140, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 122, '2016-05-21T21:50:00.000+09:00', 7, 21, 21, 1310, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-21T22:35:00.000+09:00', 120, 21, 22, 1355, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-22T09:00:00.000+09:00', 120, 22, 9, 540, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-22T16:00:00.000+09:00', 120, 22, 16, 960, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-22T21:00:00.000+09:00', 60, 22, 21, 1260, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-22T22:35:00.000+09:00', 25, 22, 22, 1355, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-23T00:00:00.000+09:00', 120, 23, 0, 0, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-23T05:00:00.000+09:00', 120, 23, 5, 300, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-23T10:00:00.000+09:00', 120, 23, 10, 600, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-23T17:00:00.000+09:00', 60, 23, 17, 1020, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-23T19:51:00.000+09:00', 31, 23, 19, 1191, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 310, '2016-05-23T20:31:00.000+09:00', 9, 23, 20, 1231, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-23T20:40:00.000+09:00', 13, 23, 20, 1240, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-23T20:56:00.000+09:00', 120, 23, 20, 1256, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-24T01:00:00.000+09:00', 120, 24, 1, 60, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-24T04:00:00.000+09:00', 120, 24, 4, 240, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-24T17:00:00.000+09:00', 120, 24, 17, 1020, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-24T20:56:00.000+09:00', 120, 24, 20, 1256, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-25T05:00:00.000+09:00', 120, 25, 5, 300, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-25T08:00:00.000+09:00', 60, 25, 8, 480, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-25T10:00:00.000+09:00', 60, 25, 10, 600, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 727, '2016-05-25T12:00:00.000+09:00', 120, 25, 12, 720, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 441, '2016-05-25T21:54:00.000+09:00', 41, 25, 21, 1314, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-25T22:36:00.000+09:00', 12, 25, 22, 1356, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-25T22:50:00.000+09:00', 10, 25, 22, 1370, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-26T00:00:00.000+09:00', 30, 26, 0, 0, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-26T00:35:00.000+09:00', 120, 26, 0, 35, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-26T06:00:00.000+09:00', 120, 26, 6, 360, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-26T11:00:00.000+09:00', 60, 26, 11, 660, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-26T13:00:00.000+09:00', 120, 26, 13, 780, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-26T22:28:00.000+09:00', 35, 26, 22, 1348, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-26T23:03:00.000+09:00', 11, 26, 23, 1383, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-26T23:14:00.000+09:00', 120, 26, 23, 1394, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-27T04:00:00.000+09:00', 120, 27, 4, 240, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-27T07:00:00.000+09:00', 120, 27, 7, 420, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-27T14:00:00.000+09:00', 60, 27, 14, 840, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 816, '2016-05-27T16:00:00.000+09:00', 120, 27, 16, 960, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-27T22:18:00.000+09:00', 45, 27, 22, 1338, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 457, '2016-05-27T23:07:00.000+09:00', 53, 27, 23, 1387, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 457, '2016-05-28T03:00:00.000+09:00', 120, 28, 3, 180, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 457, '2016-05-28T07:00:00.000+09:00', 120, 28, 7, 420, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 457, '2016-05-28T10:00:00.000+09:00', 60, 28, 10, 600, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 457, '2016-05-28T12:00:00.000+09:00', 120, 28, 12, 720, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-28T21:56:00.000+09:00', 23, 28, 21, 1316, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 310, '2016-05-28T22:20:00.000+09:00', 5, 28, 22, 1340, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 147, '2016-05-28T22:26:00.000+09:00', 34, 28, 22, 1346, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 147, '2016-05-29T00:00:00.000+09:00', 120, 29, 0, 0, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 147, '2016-05-29T03:00:00.000+09:00', 120, 29, 3, 180, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 195, '2016-05-29T15:56:00.000+09:00', 9, 29, 15, 956, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 135, '2016-05-29T16:13:00.000+09:00', 6, 29, 16, 973, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 310, '2016-05-29T16:27:00.000+09:00', 19, 29, 16, 987, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-29T16:46:00.000+09:00', 6, 29, 16, 1006, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 430, '2016-05-29T16:53:00.000+09:00', 7, 29, 16, 1013, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 839, '2016-05-29T17:30:00.000+09:00', 90, 29, 17, 1050, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 152, '2016-05-29T20:00:00.000+09:00', 13, 29, 20, 1200, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-29T20:13:00.000+09:00', 44, 29, 20, 1213, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 442, '2016-05-29T21:56:00.000+09:00', 120, 29, 21, 1316, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 442, '2016-05-30T11:00:00.000+09:00', 120, 30, 11, 660, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 442, '2016-05-30T14:00:00.000+09:00', 120, 30, 14, 840, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 466, '2016-05-30T16:51:00.000+09:00', 11, 30, 16, 1011, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 467, '2016-05-30T17:02:00.000+09:00', 19, 30, 17, 1022, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 228, '2016-05-30T17:22:00.000+09:00', 18, 30, 17, 1042, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 189, '2016-05-30T17:43:00.000+09:00', 17, 30, 17, 1063, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 178, '2016-05-30T18:15:00.000+09:00', 105, 30, 18, 1095, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 138, '2016-05-30T20:56:00.000+09:00', 10, 30, 20, 1256, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 838, '2016-05-30T21:06:00.000+09:00', 15, 30, 21, 1266, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-30T21:27:00.000+09:00', 23, 30, 21, 1287, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 442, '2016-05-30T21:54:00.000+09:00', 6, 30, 21, 1314, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 310, '2016-05-30T22:54:00.000+09:00', 8, 30, 22, 1374, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 138, '2016-05-30T23:02:00.000+09:00', 45, 30, 23, 1382, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 138, '2016-05-30T23:48:00.000+09:00', 12, 30, 23, 1428, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-31T00:14:00.000+09:00', 120, 31, 0, 14, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-31T06:00:00.000+09:00', 120, 31, 6, 360, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-31T10:00:00.000+09:00', 60, 31, 10, 600, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-31T12:00:00.000+09:00', 120, 31, 12, 720, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-31T16:00:00.000+09:00', 120, 31, 16, 960, 1.0]
['b22013ec5749f454adbc3e2444477b2b', 817, '2016-05-31T21:00:00.000+09:00', 60, 31, 21, 1260, 1.0]

In [23]:
# 피처 데이터, 레이블, 미니배치 갯수
def getMiniBatch(df_, y, n):
    if len(df_) != len(y):
        print('Feature and label num is not equal.')
        return
    start = 0
    while True:
        if start>= len(df_):
            df_ = df_.sample(frac=1).reset_index(drop=True) # 1epoch 이후 셔플
            start = 0
#         print(start)
        yield df_[start: start+n], y[start: start+n]
        start += n

In [42]:
# http://www.wildml.com/2016/08/rnns-in-tensorflow-a-practical-guide-and-undocumented-features/
# http://learningtensorflow.com/index.html
# http://suriyadeepan.github.io/2016-12-31-practical-seq2seq/

import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [43]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [46]:
with tf.variable_scope('3_batches') as scope:
    # One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
    # 3 batches 'hello', 'eolll', 'lleel'
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(
        cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)

ValueError: Variable 3_batches/rnn/basic_lstm_cell/kernel already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)

In [47]:
with tf.variable_scope('3_batches_dynamic_length') as scope:
    # One cell RNN input_dim (4) -> output_dim (5). sequence: 5, batch 3
    # 3 batches 'hello', 'eolll', 'lleel'
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(
        cell, x_data, sequence_length=[5,3,4], dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[-0.19420792, -0.07689907],
        [-0.05950917, -0.19133957],
        [-0.11797643, -0.14482792],
        [-0.15490386, -0.14862354],
        [ 0.00674692, -0.07786518]],

       [[ 0.06386328, -0.11278436],
        [ 0.15003459,  0.01929396],
        [ 0.05901301,  0.00452512],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]],

       [[-0.07841744, -0.01416886],
        [-0.12902476, -0.0313823 ],
        [-0.01846448, -0.1626779 ],
        [ 0.06416996, -0.24413343],
        [ 0.        ,  0.        ]]], dtype=float32)